spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/lottery
    username: wtongze
springdoc:
  swagger-ui:
    tags-sorter: alpha
jwt:
  secret: "this_is_a_secret"
game:
  endpoint: "lottery-proxy.wtongze.com"
